{
  config,
  lib,
  pkgs,
  mkSymlink,
  ...
}:
{
  # omamac is only relevant on Darwin: it's macOS theming (Ghostty, Neovim,
  # btop, bat, system appearance, wallpaper) driven by a Hammerspoon host.
  # `pkgs.omamac` comes from the overlay set on the pedroribeiro user in
  # flake.nix; guarding on isDarwin keeps this module evaluating cleanly on
  # Linux hosts, where that overlay isn't applied and `pkgs.omamac` doesn't
  # exist.
  home.packages = lib.optionals pkgs.stdenv.hostPlatform.isDarwin [
    pkgs.omamac
  ];

  # Generated, not symlinked: OMAMAC_DIR must be written in literally, because
  # a GUI app launched via LaunchServices (Hammerspoon.app) inherits no shell
  # environment — `home.sessionVariables` would be invisible to it.
  home.file.".hammerspoon/init.lua" = lib.mkIf pkgs.stdenv.hostPlatform.isDarwin {
    text = ''
      -- Generated by home-manager. OMAMAC_DIR is written in literally because a
      -- GUI app launched via LaunchServices inherits no shell environment.
      OMAMAC_DIR = "${pkgs.omamac}/share/omamac"
      dofile(OMAMAC_DIR .. "/hammerspoon/omamac.lua")
    '';
  };
}
