{
  config,
  lib,
  pkgs,
  mkSymlink,
  ...
}:
{
  # omamac is only relevant on Darwin: it's macOS theming (Ghostty, Neovim,
  # btop, bat, system appearance, wallpaper) driven by a Hammerspoon host.
  # `pkgs.omamac` comes from the overlay set on the pedroribeiro user in
  # flake.nix; guarding on isDarwin keeps this module evaluating cleanly on
  # Linux hosts, where that overlay isn't applied and `pkgs.omamac` doesn't
  # exist.
  home.packages = lib.optionals pkgs.stdenv.hostPlatform.isDarwin [
    pkgs.omamac
  ];

  # Generated, not symlinked: OMAMAC_DIR/OMAMAC_BIN must be written in
  # literally, because a GUI app launched via LaunchServices (Hammerspoon.app)
  # inherits no shell environment — `home.sessionVariables` would be invisible
  # to it. OMAMAC_BIN points at the WRAPPED binary flake.nix's makeWrapper
  # prefixes with jq/curl/fontconfig/bash on PATH — omamac.lua falls back to
  # the unwrapped OMAMAC_DIR/bin/omamac otherwise, which lacks that PATH.
  home.file.".hammerspoon/init.lua" = lib.mkIf pkgs.stdenv.hostPlatform.isDarwin {
    text = ''
      -- Generated by home-manager. OMAMAC_DIR/OMAMAC_BIN are written in
      -- literally because a GUI app launched via LaunchServices inherits no
      -- shell environment.
      OMAMAC_DIR = "${pkgs.omamac}/share/omamac"
      OMAMAC_BIN = "${pkgs.omamac}/bin/omamac"
      dofile(OMAMAC_DIR .. "/hammerspoon/omamac.lua")
    '';
  };
}
